development:
  adapter: mysql2
  reconnect: true
  database: rs_name_check_dev
  username: <%= APP_CONFIG['database_username'] %>
  password: <%= APP_CONFIG['database_password'] %>
  host: <%= APP_CONFIG['database_host'] %>

test:
  adapter: mysql2
  reconnect: true
  database: rs_name_check_test
  username: <%= APP_CONFIG['database_username'] %>
  password: <%= APP_CONFIG['database_password'] %>
  host: <%= APP_CONFIG['database_host'] %>

production:
  adapter: mysql2
  reconnect: true
  database: rs_name_check_prod
  username: <%= APP_CONFIG['database_username'] %>
  password: <%= APP_CONFIG['database_password'] %>
  host: <%= APP_CONFIG['database_host'] %>

